- hosts:
    - concent-deployment-server
  vars_files:
    - ../concent-builder/consts.yml
    - "{{ deployment_values }}/var.yml"
    - "{{ deployment_values }}/var-jenkins.yml"
  tasks:
    - block:
        - name:  Check if firewall rule that allows HTTP traffic exists
          shell: gcloud compute firewall-rules list    \
              --format=json                            \
              | grep allow-http-traffic
          register:      result
          ignore_errors: yes

        - name: Add firewall rule to allow http traffic
          command: gcloud compute firewall-rules create \
              allow-http-traffic                        \
              --allow=tcp:80                            \
              --priority=1000                           \
              --direction=ingress                       \
              --target-tags=http-server
          when: result.stdout == ""

        - name: Enable firewall rule for deployment server
          command: "gcloud compute instances add-tags    \
              {{ deployment_server_name }}               \
              --tags=http-server                         \
              --zone={{ gke.zone }}"
