FROM debian:{{ debian_version }}

COPY create-user.sh                     /tmp/
RUN  /tmp/create-user.sh

COPY testing.pref                                 /etc/apt/preferences.d/
COPY build-dependencies.txt                       /tmp/
COPY pyenv-build-dependencies.txt                 /tmp/
COPY signing-service/cacheable-requirements.lock  /usr/lib/signing_service/signing-service/
COPY configure-pyenv.sh                           /tmp/
COPY install-dependencies.sh                      /tmp/
COPY install-signing-service.sh                   /tmp/
COPY clean-container.sh                           /tmp/
RUN  /tmp/install-signing-service.sh
COPY middleman_protocol/                          /usr/lib/signing_service/middleman_protocol/
COPY install-middleman-protocol.sh                /tmp/
RUN  /tmp/install-middleman-protocol.sh

USER signing-service
COPY signing-service/                    /usr/lib/signing_service/signing-service/
COPY run-signing-service.sh              /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/run-signing-service.sh"]
