- become:      yes
  become_user: root
  block:
    - name:    Create user that will be used for building stuff
      user:
        name:   "{{ shared_user }}"
        state:  present

    - name:    Create data_dir
      file:
        path:  "{{ item }}"
        state: directory
        owner: "{{ shared_user }}"
        group: "{{ shared_user }}"
        mode:  0777
      with_items:
        - "{{ data_dir }}"
        - "{{ data_dir }}/concent-secrets/"
        - "{{ data_dir }}/concent-secrets/cloud/"

    - name: Upload secrets
      copy:
        src:     "{{ local_secret_dir }}/cloud/cloud-secrets.yml.vault"
        dest:    "{{ data_dir }}/concent-secrets/cloud/cloud-secrets.yml"
        decrypt: no
        owner:   "{{ shared_user }}"
        group:   "{{ shared_user }}"
