Vagrant.configure("2") do |config|
    config.vm.box      = "debian/stretch64"
    config.vm.hostname = "concent-vm"

    config.vm.network "private_network", ip: "172.30.2.3"

    config.vm.provider :virtualbox do |virtualbox|
        virtualbox.memory = 2048
        virtualbox.gui    = false
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook       = "../concent-builder/configure.yml"
        ansible.inventory_path = "./inventory"
        ansible.limit          = "all"
    end
end
