- name: Remove the build directory to get rid of files from previous builds
  file:
    path:    "{{ build_dir }}"
    state:   absent

- name: Check out working copy of concent-deployment repositories
  git:
    repo:    "{{ data_dir }}/concent-deployment"
    dest:    "{{ build_dir }}/concent-deployment"
    version: "{{ concent_versions[concent_version].versions['concent-deployment'] }}"
    clone:   yes
    update:  yes
