FROM golemfactory/blender_verifier:{{ golemfactory_blender_verifier_version }}

# Add dependencies from golem verification and concent
COPY install-dependencies.sh                  /tmp/
RUN  /tmp/install-dependencies.sh

# Build virtualenv and concent apps
COPY cacheable-requirements.lock                       /srv/http/concent_api/
COPY install-concent-api-python-dependencies.sh        /tmp/
RUN  /tmp/install-concent-api-python-dependencies.sh   python{{ python_version }}
COPY middleman_protocol                                /srv/http/middleman_protocol/
COPY install-middleman-protocol.sh                     /tmp/
RUN  /tmp/install-middleman-protocol.sh


ADD concent-api.tar                 /srv/http/
COPY concent-api-manage.sh          /usr/local/bin/
COPY run-celery.sh                  /usr/local/bin/
COPY local_settings.py              /srv/http/concent_api/concent_api/settings/

CMD ["/usr/local/bin/run-celery.sh"]
