FROM golemfactory/blender:{{ golemfactory_blender_version }}

# Add dependencies from golem verification and concent
COPY testing.pref                             /etc/apt/preferences.d/
COPY golem/imgverifier-requirements.txt       /golem/work/
COPY install-dependencies.sh                  /tmp/
RUN  /tmp/install-dependencies.sh

# Build virtualenv and concent apps
COPY requirements.lock              /srv/http/concent_api/
COPY install-concent-api.sh         /tmp/
RUN  /tmp/install-concent-api.sh


# Copy golem verification scripts
COPY golem/scripts /golem/scripts/

ADD concent-api.tar                 /srv/http/
COPY concent-api-manage.sh          /usr/local/bin/
COPY run-celery.sh                  /usr/local/bin/
COPY entrypoint.sh                  /usr/local/bin/

COPY local_settings.py              /srv/http/concent_api/concent_api/settings/

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
