- hosts:
    - concent-builder
  vars_files:
    - consts.yml
    - repositories.yml
    - ../containers/versions.yml
    - "{{ deployment_values }}/var.yml"
    - "{{ deployment_values }}/var-{{ cluster }}.yml"
    - "{{ deployment_values }}/var-jenkins.yml"
  tasks:
    - become:      yes
      become_user: jenkins
      block:
        - name: Clone concent repositories
          git:
            repo:    "{{ item.url }}"
            dest:    "{{ jenkins_home_dir }}/{{ item.name }}"
            clone:   yes
            update:  yes
            version: dev
            force:   yes
          with_items:
          #  - { url: "{{ repositories['concent-deployment'].url }}", name: concent-deployment }
            - { url: "https://github.com/bartoszbetka/concent-deployment.git", name: concent-deployment }
            - { url: "{{ deployment_values_repository }}", name: concent-deployment-values }

        - name: Create directory for concent jenkins secrets
          file:
            path:  "{{ jenkins_home_dir }}/{{ item }}"
            state: directory
          with_items:
            - concent-secrets
            - concent-secrets/{{ cluster }}/
            - concent-secrets/cloud/
            - concent-secrets/jenkins/

    - become:      yes
      become_user: root
      block:
        - name: Upload secrets
          copy:
            src:   "{{ local_secret_dir }}/{{ cluster }}/{{ item }}"
            dest:  "{{ jenkins_home_dir }}/concent-secrets/{{ cluster }}/{{ item }}"
            owner: jenkins
            group: jenkins
            mode:  0400
          with_items:
            - cluster-secrets.yml
            - "../cloud/{{ gke.service_account_name }}-private-key.json"
            - nginx-proxy-ssl.crt
            - nginx-proxy-ssl.key
            - nginx-storage-ssl.crt
            - nginx-storage-ssl.key
            - "../jenkins/.token"

        - name: Delete default user settings
          file:
            path:  /var/lib/jenkins/users/users.xml
            state: absent

        - name: Create directory for jenkins job and workspace
          file:
            path:  "{{ item }}"
            state: directory
            owner: jenkins
            group: jenkins
          with_items:
            - "/var/lib/jenkins/jobs/Build-deploy-and-test/"
            - "/var/lib/jenkins/jobs/Build-deploy-and-test/workspace"
            - "/var/lib/jenkins/users/admin/"
            - "/var/lib/jenkins/secrets/"

        - name: Upload jenkins secrets
          copy:
            src:   "{{ local_secret_dir }}/jenkins/{{ item.name }}"
            dest:  "/var/lib/jenkins{{ item.path }}{{ item.name }}"
            owner: "jenkins"
            group: "jenkins"
          with_items:
            - { path: "/users/admin/", name: "config.xml" }
            - { path: "/users/admin/", name: "apiTokenStats.xml" }
            - { path: "/", name: "credentials.xml" }
            - { path: "/secrets/", name: "master.key" }
            - { path: "/secrets/", name: "hudson.util.Secret" }

        - name: Upload jenkins configuration file
          copy:
            src:   "{{ jenkins_configuration_files_dir }}/{{ item.name }}"
            dest:  "/var/lib/jenkins{{ item.path }}{{ item.name }}"
            owner: "jenkins"
            group: "jenkins"
          remote_src: yes
          with_items:
            - { path: "/jobs/Build-deploy-and-test/", name: "config.xml" }
            - { path: "/", name: "github-plugin-configuration.xml" }

        - name: Upload jenkins template configuration file
          template:
            src:   "{{ jenkins_configuration_files_dir }}/jenkins.model.JenkinsLocationConfiguration.xml.j2"
            dest:  "/var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml"
            owner: "jenkins"
            group: "jenkins"

        - name: Restart jenkins service
          service:
            enabled: yes
            name:    jenkins
            state:   restarted

    - become:      yes
      become_user: jenkins
      block:
        - name: Wait for jenkins after restarting the daemon
          wait_for:
            port:  8080
            delay: 60

        - name: Download jenkins-cli
          get_url:
            url:   "http://{{ jenkins_address }}/jnlpJars/jenkins-cli.jar"
            dest:  "{{ jenkins_home_dir }}/jenkins-cli.jar"
            mode:  0755

        - name: Install needed plugin for jenkins
          command: java                                               \
              -jar jenkins-cli.jar                                    \
              -s http://localhost:8080/                               \
              -auth @/home/jenkins/concent-secrets/jenkins/.token     \
              install-plugin                                          \
              "{{ item }}"
          args:
            chdir: "{{ jenkins_home_dir }}/"
          with_items:
            - workflow-aggregator
            - ansible

        - name: Install github plugin for jenkins
          command: java                                               \
              -jar jenkins-cli.jar                                    \
              -s http://localhost:8080/                               \
              -auth @/home/jenkins/concent-secrets/jenkins/.token     \
              install-plugin                                          \
              github-oauth
          args:
            chdir: "{{ jenkins_home_dir }}/"

    - become:      yes
      become_user: root
      block:
        - name: Restart jenkins service
          service:
            enabled: yes
            name:    jenkins
            state:   restarted

        - name: Add nginx config
          copy:
            src:      "{{ jenkins_configuration_files_dir }}/default"
            dest:     "/etc/nginx/sites-enabled/default"
          remote_src: yes

        - name: Restart nginx service
          service:
            enabled: yes
            name:    nginx
            state:   restarted

    - become:      yes
      become_user: "{{ shared_user }}"
      block:
        - name: Check if firewall rule that allow http traffic exist
          shell: gcloud compute firewall-rules list    \
              --format=json                            \
              | grep allow-http-traffic
          register:      result
          ignore_errors: yes

        - name: Add firewall rule to allow http traffic
          command: gcloud compute firewall-rules create \
              allow-http-traffic                        \
              --allow=tcp:80                            \
              --priority=1000                           \
              --direction=ingress                       \
              --target-tags=http-server
          when: result.stdout == ""

        - name: Add firewall rule to deployment server
          command: "gcloud compute instances add-tags    \
              {{ deployment_server_name }}               \
              --tags=http-server                         \
              --zone={{ gke.zone }}"
