FROM debian:{{ debian_version }}

COPY testing.pref                                      /etc/apt/preferences.d/
COPY pyenv-build-dependencies.txt                      /tmp/
COPY configure-pyenv.sh                                /tmp/
COPY clean-pyenv-dependencies.sh                       /tmp/
COPY install-dependencies.sh                           /tmp/
RUN  /tmp/install-dependencies.sh

COPY cacheable-requirements.lock                       /srv/http/concent_api/
COPY install-concent-api-python-dependencies.sh        /tmp/
RUN  /tmp/install-concent-api-python-dependencies.sh
COPY middleman_protocol                                /srv/http/middleman_protocol/
COPY install-middleman-protocol.sh                     /tmp/
RUN  /tmp/install-middleman-protocol.sh
ADD concent-api.tar                                    /srv/http/
COPY concent-api-manage.sh                             /usr/local/bin/
COPY run-celery.sh                                     /usr/local/bin/
COPY run-gunicorn.sh                                   /usr/local/bin/
COPY local_settings.py                                 /srv/http/concent_api/concent_api/settings/

CMD ["/usr/local/bin/run-gunicorn.sh"]
