FROM debian:{{ debian_version }}

COPY testing.pref                   /etc/apt/preferences.d/
COPY install-dependencies.sh        /tmp/
RUN  /tmp/install-dependencies.sh

COPY requirements.lock              /srv/http/concent_api/
COPY install-concent-api.sh         /tmp/
RUN  /tmp/install-concent-api.sh
ADD concent-api.tar                 /srv/http/
COPY concent-api-manage.sh          /usr/local/bin/
COPY run-celery.sh                  /usr/local/bin/
COPY run-gunicorn.sh                /usr/local/bin/

COPY local_settings.py              /srv/http/concent_api/concent_api/settings/

CMD ["/usr/local/bin/run-gunicorn.sh"]
